# Site settings
title: Mike Ward, silly human
email: github@mikeward.net
description: > # this means to ignore newlines until "baseurl:"
  I need to think of something to write here soon. 
  Yep, that is all - sorry.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.mikeward.net" # the base hostname & protocol for your site
twitter_username: mightbemike
github_username:  mdw

# Build settings
markdown: kramdown
